# Generated by Django 4.0.6 on 2024-10-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0003_voto_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='votante',
            name='password',
            field=models.CharField(default='temporary_password', max_length=128),
        ),
    ]
