# Generated by Django 4.0.6 on 2024-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0004_votante_last_login_votante_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='ha_votado',
            field=models.BooleanField(default=False),
        ),
    ]
