# Generated by Django 4.0.6 on 2024-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0005_votante_ha_votado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('numero', models.CharField(max_length=25, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='fotoLista')),
            ],
        ),
    ]
