# Generated by Django 4.0.6 on 2024-11-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0006_listas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listas',
            new_name='Lista',
        ),
    ]
