# Generated by Django 4.0.6 on 2024-11-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0007_rename_listas_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='candidato',
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
