# Generated by Django 4.0.6 on 2024-11-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0010_candidato_remove_voto_cargo_delete_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.AddField(
            model_name='lista',
            name='rol',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('1ER VOCAL PRINCIPAL', '1er Vocal Principal'), ('2DO VOCAL PRINCIPAL', '2do Vocal Principal'), ('3ER VOCAL PRINCIPAL', '3er Vocal Principal'), ('1ER VOCAL SUPLENTE', '1er Vocal Suplente'), ('2DO VOCAL SUPLENTE', '2do Vocal Suplente'), ('3ER VOCAL SUPLENTE', '3er Vocal Suplente')], default='PRESIDENTE', max_length=25),
        ),
    ]
