# Generated by Django 4.0.6 on 2024-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0012_remove_lista_rol_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='votante',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
