# Generated by Django 4.0.6 on 2024-11-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0013_remove_votante_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='ha_votado',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='password',
        ),
        migrations.AddField(
            model_name='voto',
            name='lista_votada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Votaciones.lista'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='ci',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='votante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
