# Generated by Django 4.0.6 on 2024-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0014_remove_votante_ha_votado_remove_votante_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
