# Generated by Django 5.1.3 on 2024-11-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0020_voto_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='lista',
        ),
    ]
