# Generated by Django 5.1.3 on 2024-11-22 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0022_voto_lista_tolal_votos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='lista_tolal_votos',
        ),
        migrations.AddField(
            model_name='voto',
            name='lista_total_votos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_votos', to='Votaciones.lista'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='lista_votada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='Votaciones.lista'),
        ),
    ]
